[package]
name = "qcms-lcms-transform-comparison"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.5"
lcms2 = "6.1.0"
qcms = { git = "https://github.com/FirefoxGraphics/qcms.git", rev = "2ee13006ac1d17d10a53fb5b89ecd6513211c1c3" }
